version: '3'
services:
  donotping:
    build: .
    environment:
      - NODE_ENV=production
      - RHOST=redis
    networks:
      - redis-net
    depends_on:
      - redis
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
